In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
NB_CLASSES = 10
RESHAPED = 784

In [ ]:
model = tf.keras.models.Sequential()

In [ ]:
model.add(
    keras.layers.Dense(NB_CLASSES,
                       input_shape=(RESHAPED,),
                       kernel_initializer='zeros',
                       name='dense_layer',
                       activation='softmax')
)

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_layer (Dense)         (None, 10)                7850      
                                                                 
Total params: 7850 (30.66 KB)
Trainable params: 7850 (30.66 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
#MNIST Handwritten example
import numpy as np

In [ ]:
EPOCHS = 200
BATCH_SIZE = 128
VERBOSE = 1
NB_CLASSES = 10 # number of outputs = number of digits (0-9)
N_HIDDEN = 128
VALIDATION_SPLIT = 0.2

In [ ]:
#Loading MNIST dataset
mnist = keras.datasets.mnist

In [ ]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
X_train.shape

(60000, 28, 28)

In [ ]:
X_test.shape

(10000, 28, 28)

In [ ]:
# reshape X_train to 60000, 784
RESHAPED = 784

In [ ]:
X_train = X_train.reshape(60000, RESHAPED)
X_test = X_test.reshape(10000, RESHAPED)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

In [ ]:
X_train.shape, X_test.shape

((60000, 784), (10000, 784))

In [ ]:
len(X_train[0])

784

In [ ]:
# Normalize the inputs to be within in [0,1]
X_train /= 255
X_test /= 255

print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

60000 train samples
10000 test samples


In [ ]:
# One hot representation of the labels
y_train = tf.keras.utils.to_categorical(y_train, NB_CLASSES)
y_test = tf.keras.utils.to_categorical(y_test, NB_CLASSES)

In [ ]:
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [ ]:
#Model
model = tf.keras.models.Sequential()
model.add(
    keras.layers.Dense(
        NB_CLASSES,
        input_shape=(RESHAPED, ),
        name='dense_layer',
        activation='softmax'
    )
)

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_layer (Dense)         (None, 10)                7850      
                                                                 
Total params: 7850 (30.66 KB)
Trainable params: 7850 (30.66 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
#Compliling the model
model.compile(
    optimizer='SGD',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [ ]:
#Training the model
model.fit(
    X_train, y_train,
    batch_size=BATCH_SIZE,
    epochs=EPOCHS,
    verbose=VERBOSE,
    validation_split=VALIDATION_SPLIT
)

Epoch 1/200
375/375 [==============================] - 1s 2ms/step - loss: 1.4149 - accuracy: 0.6521 - val_loss: 0.9042 - val_accuracy: 0.8285
Epoch 2/200
375/375 [==============================] - 1s 2ms/step - loss: 0.7997 - accuracy: 0.8280 - val_loss: 0.6589 - val_accuracy: 0.8622
Epoch 3/200
375/375 [==============================] - 1s 2ms/step - loss: 0.6462 - accuracy: 0.8489 - val_loss: 0.5623 - val_accuracy: 0.8718
Epoch 4/200
375/375 [==============================] - 1s 2ms/step - loss: 0.5728 - accuracy: 0.8604 - val_loss: 0.5088 - val_accuracy: 0.8797
Epoch 5/200
375/375 [==============================] - 1s 2ms/step - loss: 0.5282 - accuracy: 0.8676 - val_loss: 0.4747 - val_accuracy: 0.8829
Epoch 6/200
375/375 [==============================] - 1s 2ms/step - loss: 0.4977 - accuracy: 0.8729 - val_loss: 0.4504 - val_accuracy: 0.8858
Epoch 7/200
375/375 [==============================] - 1s 2ms/step - loss: 0.4751 - accuracy: 0.8774 - val_loss: 0.4322 - val_accuracy: 0.8896

In [ ]:
#Evaluate the model
test_loss, test_acc = model.evaluate(X_test, y_test)
print('Test loss', test_loss)
print('Test accuracy', test_acc)

313/313 [==============================] - 0s 1ms/step - loss: 0.2779 - accuracy: 0.9228
Test loss 0.2779472768306732
Test accuracy 0.9228000044822693


In [ ]:
# Improving the neural net

In [ ]:
EPOCHS = 50
BATCH_SIZE = 128
VERBOSE = 1
NB_CLASSES = 10
N_HIDDEN = 128
VALIDATION_SPLIT = 0.2

In [ ]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
RESHAPED = 784

In [ ]:
X_train = X_train.reshape(60000, RESHAPED)
X_test = X_test.reshape(10000, RESHAPED)
X_train.astype('float32')
X_test.astype('float32')

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
X_train, X_test = X_train / 255.0, X_test / 255.0

In [ ]:
X_train.shape, X_test.shape

((60000, 784), (10000, 784))

In [ ]:
y_train = tf.keras.utils.to_categorical(y_train, NB_CLASSES)
y_test = tf.keras.utils.to_categorical(y_test, NB_CLASSES)

In [ ]:
# Build the model

In [ ]:
model = tf.keras.models.Sequential()
model.add(
    keras.layers.Dense(N_HIDDEN,
                       input_shape=(RESHAPED,),
                       name='dense_layer',
                       activation='relu')
)
model.add(
    keras.layers.Dense(
        N_HIDDEN,
        name='dense_layer_2',
        activation='relu'
    )
)
model.add(
    keras.layers.Dense(NB_CLASSES,
                       name='dense_layer_3',
                       activation='softmax')
)

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_layer (Dense)         (None, 128)               100480    
                                                                 
 dense_layer_2 (Dense)       (None, 128)               16512     
                                                                 
 dense_layer_3 (Dense)       (None, 10)                1290      
                                                                 
Total params: 118282 (462.04 KB)
Trainable params: 118282 (462.04 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
# Compile the model

In [ ]:
model.compile(
    optimizer='SGD',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [ ]:
# Train the model

In [ ]:
model.fit(
    X_train, y_train, batch_size=BATCH_SIZE, epochs=EPOCHS, verbose=VERBOSE,
    validation_split=VALIDATION_SPLIT
)

Epoch 1/50
375/375 [==============================] - 2s 3ms/step - loss: 1.4823 - accuracy: 0.6399 - val_loss: 0.7474 - val_accuracy: 0.8543
Epoch 2/50
375/375 [==============================] - 1s 3ms/step - loss: 0.5857 - accuracy: 0.8626 - val_loss: 0.4461 - val_accuracy: 0.8878
Epoch 3/50
375/375 [==============================] - 1s 3ms/step - loss: 0.4280 - accuracy: 0.8865 - val_loss: 0.3683 - val_accuracy: 0.9005
Epoch 4/50
375/375 [==============================] - 1s 3ms/step - loss: 0.3718 - accuracy: 0.8973 - val_loss: 0.3335 - val_accuracy: 0.9076
Epoch 5/50
375/375 [==============================] - 1s 3ms/step - loss: 0.3406 - accuracy: 0.9040 - val_loss: 0.3102 - val_accuracy: 0.9138
Epoch 6/50
375/375 [==============================] - 2s 4ms/step - loss: 0.3187 - accuracy: 0.9109 - val_loss: 0.2944 - val_accuracy: 0.9179
Epoch 7/50
375/375 [==============================] - 1s 4ms/step - loss: 0.3021 - accuracy: 0.9139 - val_loss: 0.2833 - val_accuracy: 0.9212
Epoch 

In [ ]:
# Evaluate the model

In [ ]:
test_loss, test_acc = model.evaluate(X_test, y_test)
test_acc

313/313 [==============================] - 0s 1ms/step - loss: 0.1218 - accuracy: 0.9633


0.9632999897003174

# **Improving the network with dropout**

In [27]:
EPOCHS = 200
BATCH_SIZE = 128
VERBOSE = 1
NB_CLASSES = 10
N_HIDDEN = 128
VALIDATION_SPLIT = 0.2
DROPOUT = 0.3

In [28]:
mnist = keras.datasets.mnist

In [30]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [31]:
RESHAPED = 784

In [33]:
X_train = X_train.reshape(60000, RESHAPED)
X_test = X_test.reshape(10000, RESHAPED)
X_train.astype('float32')
X_test.astype('float32')

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [34]:
# Normalize inputs within [0, 1]
X_train, X_test = X_train / 255.0, X_test / 255.0

In [35]:
# One-hot representation for labels
y_train = tf.keras.utils.to_categorical(y_train, NB_CLASSES)
y_test = tf.keras.utils.to_categorical(y_test, NB_CLASSES)

In [36]:
# Building the model

In [37]:
model = tf.keras.models.Sequential()

In [38]:
model.add(
    keras.layers.Dense(
        N_HIDDEN,
        input_shape=(RESHAPED, ),
        name='dense_layer',
        activation='relu'
    )
)
model.add(
    keras.layers.Dropout(DROPOUT)
)
model.add(
    keras.layers.Dense(
        N_HIDDEN,
        name='dense_layer_2',
        activation='relu'
    )
)
model.add(
    keras.layers.Dense(
        NB_CLASSES,
        name='dense_layer_3',
        activation='softmax'
    )
)

In [39]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_layer (Dense)         (None, 128)               100480    
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_layer_2 (Dense)       (None, 128)               16512     
                                                                 
 dense_layer_3 (Dense)       (None, 10)                1290      
                                                                 
Total params: 118282 (462.04 KB)
Trainable params: 118282 (462.04 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [40]:
# Compiling the model
model.compile(
    optimizer='SGD',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [42]:
# Train the model
model.fit(
    X_train, y_train,
    batch_size=BATCH_SIZE,
    epochs=EPOCHS,
    verbose=VERBOSE,
    validation_split=VALIDATION_SPLIT
)

Epoch 1/200
375/375 [==============================] - 2s 3ms/step - loss: 1.6172 - accuracy: 0.5228 - val_loss: 0.8284 - val_accuracy: 0.8154
Epoch 2/200
375/375 [==============================] - 1s 3ms/step - loss: 0.7810 - accuracy: 0.7749 - val_loss: 0.4981 - val_accuracy: 0.8742
Epoch 3/200
375/375 [==============================] - 2s 4ms/step - loss: 0.5882 - accuracy: 0.8273 - val_loss: 0.4044 - val_accuracy: 0.8907
Epoch 4/200
375/375 [==============================] - 1s 3ms/step - loss: 0.5028 - accuracy: 0.8534 - val_loss: 0.3575 - val_accuracy: 0.9018
Epoch 5/200
375/375 [==============================] - 1s 3ms/step - loss: 0.4544 - accuracy: 0.8684 - val_loss: 0.3268 - val_accuracy: 0.9085
Epoch 6/200
375/375 [==============================] - 1s 3ms/step - loss: 0.4162 - accuracy: 0.8805 - val_loss: 0.3058 - val_accuracy: 0.9125
Epoch 7/200
375/375 [==============================] - 1s 3ms/step - loss: 0.3917 - accuracy: 0.8863 - val_loss: 0.2891 - val_accuracy: 0.9183

In [43]:
# Evaluate the model
test_loss, test_acc = model.evaluate(X_test, y_test)
test_acc

313/313 [==============================] - 0s 1ms/step - loss: 0.0723 - accuracy: 0.9779


0.9779000282287598